nelmio_api_doc:
    documentation:
        info:
            title: Black Jack API
            description: Compute probability to bust
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!(_error|doc)) # Accepts routes under / except /doc and /_errors
