services:
    monolog.formatter.prod:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - " >    %%datetime%% [%%level_name%%] %%message%%\n >>   %%context%%\n\n"
            - "H:i:s"
            - false
            - false

monolog:
    handlers:
        main:
            type: stream
            path: path: 'php://stdout'
            level: info
            formatter: monolog.formatter.prod
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
